server:
  port: 8761
eureka:
  instance:
    hostname: stormy-citadel-28405.herokuapp.com
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:8761/eureka
    registerWithEureka: false
    fetchRegistry: false