server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:8761/eureka
    registerWithEureka: false
    fetchRegistry: false